services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:///app/db/development.sqlite3
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
